### ISSUE TITLE
Rename to `diaktoros` or clarify in `README.md`

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zend-diactoros#1]
As per this amazingly informative graphic representation: http://www.googlefight.com/index.php?word1=diactoros&word2=diaktoros

(and as per discussion on IRC)

Yes, it may be a typo like "symfony" (intentional), still not sure tho.

That said, this is nitpicking :-)

**Comment by bakura10** [comment]
Seems to be Diactoros ^^.

![](https://s3.amazonaws.com/f.cl.ly/items/1u3d3e1a2o0a1g3q0J0F/Capture%20d%E2%80%99e%CC%81cran%202015-05-21%20a%CC%80%2021.07.39.png)

**Comment by Ocramius** [comment]
@bakura10 works for me as long as it's not considered a typo :-)

**Comment by weierophinney** [comment]
From what I've found, they're both valid spellings. The version with a "k" is the traditional Greek, while the version with a "c" is the latinized variant. Since the goal was to have something unique in the PHP namespace that had a "message" or "messenger" semantic, I think we're in good shape.
