### ISSUE TITLE
Uri::__toString to display port when using non-default port

### ISSUE THREAD

**Issue by mdecaffmeyer** [zendframework/zend-diactoros#105]
Wouldn't it be nice to display the port in the url if the port is not the default one for that scheme?

E.g. port 80 with http protocol wouldn't display the port in the url, however 8080 would.

**Comment by Ocramius** [comment]
@mdecaffmeyer did you close by accident or was this already solved?

**Comment by mdecaffmeyer** [comment]
@Ocramius it is already implemented, I am sorry (I missed it because I changed port, see that it didn't work as I wanted, but then remembered that the request is immutable).

**Comment by Ocramius** [comment]
@mdecaffmeyer thanks for clarifying!
