### ISSUE TITLE
Merge develop on master and tag a new release?

### ISSUE THREAD

**Issue by mnapoli** [zendframework/zend-diactoros#106]
Hi, I would like to use PRs that were merged into `develop`. Unfortunately develop hasn't been merged into master and released for a few months. When is the next release planned?

**Comment by Ocramius** [comment]
@mnapoli could you link to what exactly you'd need? Could be helpful meanwhile.

**Comment by weierophinney** [comment]
@mnapoli I'll see if I can get this scheduled soon; there's still a few features for 1.2.0 that are not complete yet.

**Comment by weierophinney** [comment]
Done!

**Comment by mnapoli** [comment]
Oh well awesome thank you!
