### ISSUE TITLE
SapiEmitter with big streams

### ISSUE THREAD

**Issue by oscarotero** [zendframework/zend-diactoros#107]
Hello.
I have a use case with a big file (a mp4 video) that needs to be emitted but I get an out of memory error. This is because the body is emitted at one time [with an echo](https://github.com/zendframework/zend-diactoros/blob/master/src/Response/SapiEmitter.php#L101):
```php
echo $response->getBody();
```
Is there any reason for that? Why not emit the body as a stream? Something like:
```php
$body = $response->getBody();
$body->rewind();

while (!$body->eof()) {
    echo $body->read(8192);
}
```
I can make a PR, if you like.
Thanks

**Comment by weierophinney** [comment]
In benchmarks I performed earlier this year, I found that for the majority use case — emitting HTML generated from a template — a simple `echo` was orders of magnitude faster. For cases where you need to emit an actual stream, I'd create an alternate emitter.

However, if that's done in a SAPI environment, there's a small problem currently: most methods in the SapiEmitter are marked private. We have a couple options from here:

- Move those methods into a trait, and compose the trait into `SapiEmitter`. That provides a relatively easy path for creating alternate implementations.
- Make the methods protected; that allows for extension.
- Create a "SapiStreamEmitter" implementation that does the above to emit the body. This does not preclude the previous points.

If you'd like to do a PR, I'd suggest doing a PR that addresses one of the first two options, and then a separate one for the stream-centric emitter.

Thanks in advance!

**Comment by oscarotero** [comment]
I was thinking in a `$maxBufferSize` argument passed to constructor that the emitBody can handle. So, if it's `null` (by default), it works like it does currently, but if it's a number, uses a `while` to emit the content.
But your options are fine too (I'd preffer the trait).
