### ISSUE TITLE
Raise exception on write() if stream is not writeable

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zend-diactoros#13]
As noted in [a comment on zfr-oauth2-server](https://github.com/zf-fr/zfr-oauth2-server/pull/31/files#r30953668), `Stream::write()` does not currently raise an exception when writing to a stream that is not writeable. This causes silent errors when working with the `php://` streams, as they will not raise notices for operations they cannot fulfill.

**Comment by Ocramius** [comment]
To be handled in #15

**Comment by Ocramius** [comment]
Handled in #15
