### ISSUE TITLE
Silent no seekable stream exception

### ISSUE THREAD

**Issue by qpautrat** [zendframework/zend-diactoros#163]
As you probably already know, prior to PHP 5.6, `php://input` stream is not [seekable](http://php.net/manual/en/wrappers.php.php).

I would like to know why you silent this [exception](https://github.com/zendframework/zend-diactoros/blob/master/src/Stream.php#L160) in `__toString()` [method](https://github.com/zendframework/zend-diactoros/blob/master/src/Stream.php#L54).

It seems a little bit strange. If my stream can not be rewind, i would like to know it instead of get an empty string.

**Comment by n0o0bSina** [comment]
Hi
We can't throw exception in `__toString` method.
http://php.net/manual/en/language.oop5.magic.php#object.tostring

**Comment by qpautrat** [comment]
Honestly I never test it but the way I understand there is nothing saying it is mandatory to catch exception in __toString() method. The function in this contexte does not throw the exception, it just catches it and silents it by returning an empty string.

**Comment by Ocramius** [comment]
If you throw in `__toString()`, php will fatal. We need to fix the initial
condition that leads to the un-seekable stream first.

**Comment by qpautrat** [comment]
I tested it this morning. I didn't ever encounter this fatal error, happy to know it. 
Thanks :+1:
