### ISSUE TITLE
Headers from REDIRECT_HTTP_* environment variables

### ISSUE THREAD

**Issue by franzliedke** [zendframework/zend-diactoros#164]
Hello,

at Flarum, we've come across some fancy server configurations so far.

Apparently, some Apache modules strip HTTP headers (most importantly, the `Authorization` header, for "security reasons"). It is often recommended to fix this by storing the header in a custom environment variable, e.g. like this:

~~~
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
~~~

Apparently, PHP then prefixes the header with a `REDIRECT_`, which causes Diactoros' header detection to ignore it. Some apps have [built their own workarounds](https://git.dev.so/lab/request/commit/c82dd7c0b703f096258540a66c94772f2ebdc20b).

Questions?
- Does it make sense to put this in a library like this, as it seems to be a very common workaround?
- Apparently, there are options for at least some of these Apache modules that properly enable the header to be passed (e.g. `FastCgiServer filename -pass-header Authorization`). That would technically be the *correct* workaround and puts the burden on the server administrator. Are there workarounds like that for every case?
- It's so hard to find proper documentation on this... :(

For reference:
https://github.com/flarum/core/issues/384
https://github.com/zendframework/zf2/issues/5873

**Comment by weierophinney** [comment]
> Does it make sense to put this in a library like this, as it seems to be a very common workaround?

Yes. `ServerRequstFactory` is trying to accommodate the most common environments, so we would definitely like to see it in place.

Are you willing to work up a pull request?

**Comment by franzliedke** [comment]
Yes, I'm on it. I finally found a [rather extensive explanation](http://stackoverflow.com/a/10128290/192741) about this, too. It looks like the culprit is not necessarily the passing through of these variables, but rather Apache's behavior when dealing with environment variables set by rewrite rules.

So, by doing the following, we could possibly prevent other similar problems in the future:
- Treat all environment variables that start with `REDIRECT_` as if they did not exist.
- Add both the `REDIRECT_xyz` and the `xyz` variant to the request.

How would we deal with conflicts? I'm currently leaning towards not overwriting `HTTP_AUTHORIZATION` with `REDIRECT_HTTP_AUTHORIZATION` if the former already exists.

Whew, server config stuff is hard. Hat tip to you for trying to support all of this. ;)
