### ISSUE TITLE
question on RequestInterface cloning

### ISSUE THREAD

**Issue by pine3ree** [zendframework/zend-diactoros#177]
should we clone the internal UriInterface instance with __clone()? otherwise the clones will point to the original instance's uri.

**Comment by weierophinney** [comment]
They can point to the same instance; there's no need to clone the Uri instance *unless the Uri has changed*, which would result in a new request instance anyways.

**Comment by pine3ree** [comment]
@weierophinney oh yes...I remember now i asked myself the same question long time ago then answering the same way ...really sorry about that....
