### ISSUE TITLE
CallbackStream is incompatible with SapiStreamEmitter

### ISSUE THREAD

**Issue by markstory** [zendframework/zend-diactoros#199]
I'm not sure if this is intentional, but the current `CallbackStream` implementation is not compatible with `SapiStreamEmitter`. Because `CallbackStream` throws an exception on `rewind()` it cannot be combined with `SapiStreamEmitter`. A trivial example would be

```php
$fp = imagecreatefrompng('/path/to/meme.png');
$response = new Response();
$response = $response
  ->withHeader('Content-Type', 'image/png')
  ->withBody(new CallbackStream(function () use ($fp) {
    imagepng($fp);
    imagedestroy($fp);
  });

$emitter = new SapiStreamEmitter();
$emitter->emit($response);
```

Is there a reason that the `SapiStreamEmitter` is incompatible with `CallbackStream`, or should frameworks/applications be inspecting the response stream and choosing the correct emitter based stream type?

Related to cakephp/cakephp#9408

**Comment by weierophinney** [comment]
> Is there a reason that the SapiStreamEmitter is incompatible with CallbackStream,

No, not really. :smile:

When I created the `CallbackStream`, I considered a `rewind()` operation as problematic; you can't "rewind" a code invocation. As such, I had it raise an exception.

There are two potential possibilities here:

- We update the `SapiStreamEmitter` to not call `rewind()` if it detects a `CallbackStream`.
- We update `CallbackStream` to no longer throw an exception on `rewind()`.

I'm okay with either, though probably more okay with the second; would you be willing to create a PR, @markstory ?

**Comment by markstory** [comment]
Would be checking if the stream `isSeekable` before rewinding work for you? That's what I ended up doing in CakePHP as a temporary measure.

**Comment by weierophinney** [comment]
Ooh! I like that even better! Go for it!
