### ISSUE TITLE
Make PhpInputStream readable by PHP's naitive stream functions (or not)

### ISSUE THREAD

**Issue by PeteDevoy** [zendframework/zend-diactoros#209]
Apologies in advance because I realise this is most likely not an issue but by design.

Is it right that I should not be able to do something like:
```php

$request  = Zend\Diactoros\ServerRequestFactory::fromGlobals();
$document = simplexml_load_file($request->getBody()); //errors due to trying to read file at
                                                      //return value of __toString()

//could instead try to read stream name ('php://input') from PhpInputStream object...
$file = fopen($request->getBody()->stream); //...errors because ->stream is a protected property
```
Is the intention we extend `Zend\Diactoros\PhpInputStream` and write a public method to expose `->stream`?

Based off my SO question: http://stackoverflow.com/questions/39665780/pass-stream-wrapped-by-zend-diactoros-phpinputstream-psr-7-streaminterface-to

**Comment by weierophinney** [comment]
`$request->getBody()` returns a PSR-7 `StreamInterface` (in this case, a `Zend\Diactoros\Stream` instance), which cannot be used with `simplexml_load_file()`; you should instead do:

```php
$document = simplexml_load_string((string) $request->getBody());
```

If you want access to the underlying stream instead, we have the `detach()` method; however, once you do that, the `Stream` instance is no longer usable (the method unsets the underlying resource, as we can no longer calculate position, size, etc.). Doing so would look like:

```php
$document = simplexml_load_file($request->getBody()->detach());
```

**Comment by PeteDevoy** [comment]
Thanks for your help, that makes a lot of sense.

For anyone else who finds this, I am now doing this:

```php
$stream = $request->getBody()->detach();
$metadata = stream_get_meta_data($stream);
$document = simplexml_load_file($metadata['uri']);

```
Feels a little convoluted but maybe it's just a shortcoming in simplexml_load_file that it can't accept a stream resource.
