### ISSUE TITLE
SapiStreamEmitter::emit() - high memory usage - memory exhaust 

### ISSUE THREAD

**Issue by fcabralpacheco** [zendframework/zend-diactoros#223]
I'm working on a project where the application acts as proxy/cache for internal network requests.

When SapiStreamEmitter::emit() is called, it ends up generating a high memory usage, or reaches the limits imposed by the PHP configuration.

This only occurs when the stream is not seekable, and SapiStreamEmitter::emit() uses the stream::toString() or stream::getContents() to get the full contents from stream and store it in memory (eg: echo $body;).

At first, I looked for other related issues, and by the comments I accepted that the behavior of the emitter was the expected, and ended up creating a custom emitter for application.

But over time I started to think that it was strange by default to use a stream and not make use of its capabilities to reduce memory usage.

I understand that the stream::toString() and stream::getContents() performance are superior to a sequence of stream::read(), but I think in a more general way when using streams, you can use the stream::read() when the stream is readable, and not only when it is seekable.

I implemented a possible fix:

https://github.com/fcabralpacheco/zend-diactoros/commit/c90ca44ece17b6120b9c9d8d2560cf0b2a9d9662

Do you think this would be a good solution?

**Comment by Ocramius** [comment]
> This only occurs when the stream is not seekable, and SapiStreamEmitter::emit() uses the stream::toString() or stream::getContents() to get the full contents from stream and store it in memory (eg: echo $body;).

`stream::toString()` and `stream::getContents()` will obviously cause a lot of memory usage.

The patch you provided looks interesting for readable streams: can you send it as a pull request for review?
