### ISSUE TITLE
JsonResponse not working

### ISSUE THREAD

**Issue by Wikiki** [zendframework/zend-diactoros#225]
Hello,

I try to use the JsonResponse but without success.
I use the following code to send an array as response content
`return new JsonResponse( $data, $status );`

Then I use the following code to emit the response
```
$emitter = new SapiStreamEmitter();
$emitter->emit( $response );
```

But in my browser the response is empty. I always get a HTTP Status code 200 with an empty body. Even if I force status code to 201 (for example).

Can you help me ?

Regards.

**Comment by fcabralpacheco** [comment]
I wasn't able to reproduce the issue in the tests.

The behavior appears to be headers already sent and display_errors = Off.

What is your error reporting configuration (in phpinfo(), error reporting and display_errors directives)?

**Comment by Wikiki** [comment]
Hi,

the directives are the following:
display_errors = Off
error_reporting = 32767

**Comment by Wikiki** [comment]
Hi again,

You're right...if I put display_errors to on then I got a PHP error. After fixing it it's working perfectly.
Thanks for your help.
