### ISSUE TITLE
PhpInputStream and '0' chunks

### ISSUE THREAD

**Issue by kelunik** [zendframework/zend-diactoros#255]
`PhpInputStream::read` doesn't add `"0"` chunks to `$this->cache`, because the [first condition of the `if`](https://github.com/zendframework/zend-diactoros/blob/fbcf611e8766a599c4839da569f5e2d267ddf201/src/PhpInputStream.php#L62) evaluates to `false`.

**Comment by Ocramius** [comment]
This would need a minimal test: as-is, the issue is a bit cryptic

**Comment by sasezaki** [comment]
I think reproducible by below code.

```php
<?php
use Zend\Diactoros\PhpInputStream;

$stream = new PhpInputStream('data://,a');
$stream->read(1); // read 'a'
$stream->read(1); // read 'EOF'
var_dump($stream->getContents()); // string(1) "a"

$stream = new PhpInputStream('data://,0');
$stream->read(1); // read '0' - not cached
$stream->read(1); // read 'EOF'
var_dump($stream->getContents()); // string(0) ""
```
