### ISSUE TITLE
Stream::__toString() doesn't attempt to seek to the beginning

### ISSUE THREAD

**Issue by kelunik** [zendframework/zend-diactoros#256]
PSR-7 says:

> This method MUST attempt to seek to the beginning of the stream before reading data and read the stream until the end is reached.

Note that it shouldn't do that in `getContents()`:

> Returns the remaining contents in a string

**Comment by weierophinney** [comment]
We `rewind()` currently; see this line for details: https://github.com/zendframework/zend-diactoros/blob/e81e871c235aa914a315c8fe360c74ef7dfb4c9c/src/Stream.php#L52

`rewind()` is semantically equivalent to `seek(0)`: https://github.com/zendframework/zend-diactoros/blob/e81e871c235aa914a315c8fe360c74ef7dfb4c9c/src/Stream.php#L178-L181

`getContents()` does not and never has done a `seek()` operation.

**Comment by kelunik** [comment]
Sorry, I think I meant `PhpInputStream`, but that appends to the cache and doesn't return the result of `getContents()`, but `$this->cache`.

https://github.com/zendframework/zend-diactoros/blob/55e793bbe8af9b448f1c1ef8aa1f2cccfe441a21/src/PhpInputStream.php#L40-L45
