### ISSUE TITLE
PDOStatement to StreamInterface

### ISSUE THREAD

**Issue by CMCDragonkai** [zendframework/zend-diactoros#262]
If I wanted to stream out SQL results using the `Traversable` PDOStatement, would this involve creating a wrapper around PDOStatement that implements the StreamInterface? And if so, does this mean I should be definitely using the `SapiStreamEmitter`?

**Comment by weierophinney** [comment]
> would this involve creating a wrapper around PDOStatement that implements the StreamInterface?

Yes. This was one of the use cases posited by PSR-7, and which informed the idea of having streams represent the body contents.

> does this mean I should be definitely using the SapiStreamEmitter?

Yes.

If you switch to [zend-httphandlerrunner](https://docs.zendframework.com/zend-httphandlerrunner/), we now provide an `EmitterStack`, and document how to [conditionally use the SapiStreamEmitter](https://docs.zendframework.com/zend-httphandlerrunner/emitters/#conditionally-using-the-sapistreamemitter).
