### ISSUE TITLE
Inconsistent URL path handler (leading slashes)

### ISSUE THREAD

**Issue by Visualq** [zendframework/zend-diactoros#263]
If the path for a request for example contains leading slashes like: `////slug////slug2/// `
the getPath() method on the Uri component returns:
`/slug////slug2///` (converted the leading slashes to a single slash) which in my opinion is incorrect and should be `////slug////slug2///`. According to the code in Uri.php It's done to prevent XSS attempts. However I don't see how?

**Comment by sharifzadesina** [comment]
this is cause of PSR-7 standard, I think you have to create an issue [here](https://github.com/php-fig/http-message).
