### ISSUE TITLE
How to pronounce "diactoros" ?

### ISSUE THREAD

**Issue by sasezaki** [zendframework/zend-diactoros#27]
Please provide Phonetic transcription or pronounce_diactoros.mp3 link at README.

It needs for developer's communication.

**Comment by weierophinney** [comment]
dee-ack-tor-ous, if that helps. I don't know phonetic transcription, unfortunately.

**Comment by ezimuel** [comment]
This is the phonetic transcription of "diactoros" or "diaktoros" /dɪʌktɒrɒs/.

**Comment by sasezaki** [comment]
thanks! @ezimuel
