### ISSUE TITLE
Error parse cookie from header

### ISSUE THREAD

**Issue by StApostol** [zendframework/zend-diactoros#272]
Client send cookie
`PHPSESSID=mckio0avb9bkminedcftmsrcrf; cookie_region=7; CakeCookie[cookie_region]=7`

And method parseCookieHeader return array only with 2 elements PHPSESSID and cookie_region.
But in $_COOKIE I have 3 elements
`
Array
(
    [PHPSESSID] => mckio0avb9bkminedcftmsrcrf
    [cookie_region] => 7
    [CakeCookie] => Array
        (
            [cookie_region] => 7
        )

)`

**Comment by Ocramius** [comment]
Those are 3 elements:

```
PHPSESSID=mckio0avb9bkminedcftmsrcrf; cookie_region=7; CakeCookie[cookie_region]=7
```

 * `PHPSESSID=mckio0avb9bkminedcftmsrcrf;`
 * `cookie_region=7;`
 * `CakeCookie[cookie_region]=7` (which is parsed to an array)
