### ISSUE TITLE
PHP Fatal error:  Class Zend\Diactoros\Request contains 9 abstract methods and must therefore be declared abstract or implement the remaining methods

### ISSUE THREAD

**Issue by brandonexa** [zendframework/zend-diactoros#274]
Hi,

I was trying to run ChartMogul API in billing system, after that I have received this error message. But I have no idea what is wrong? Anyone can help me?

The error:
PHP Fatal error:  Class Zend\Diactoros\Request contains 9 abstract methods and must therefore be declared abstract or implement the remaining methods (Psr\Http\Message\MessageInterface::getProtocolVersion, Psr\Http\Message\MessageInterface::withProtocolVersion, Psr\Http\Message\MessageInterface::hasHeader, ...) in /home/vdhos/public_html/billing/modules/admin/chartmogul/vendor/zendframework/zend-diactoros/src/Request.php on line 73

Thanks.

**Comment by weierophinney** [comment]
My guess is you're using a PHP version prior to 5.4.0, when traits were introduced. We use traits to provide implementations of a number of methods defined in the PSR-7 interfaces.
