### ISSUE TITLE
JSON requests not parsed when using ServerRequestFactory

### ISSUE THREAD

**Issue by RinkAttendant6** [zendframework/zend-diactoros#278]
The body of JSON requests is not being populated into the `parsedBody` property of the `ServerRequest` object when using `\Zend\Diactoros\ServerRequestFactory::fromGlobals`. In fact, nothing appears to be parsed at all. Please see the following example:

Request (only relevant parts included):
```
Content-Type: application/json

{"foo": "bar"}
```

Code:
```php
$request = \Zend\Diactoros\ServerRequestFactory::fromGlobals($_SERVER, $_GET, $_POST, $_COOKIE, $_FILES);
print_r($request->getParsedBody());
```

Result:
```
Array
(
)
```

Expected result:
```
Array
(
    [foo] => bar
)
```

**Comment by Xerkus** [comment]
Works as intended.
zend-diactoros does not perform content negotiation. It is a responsibility of application, for example
in zend-expressive: https://docs.zendframework.com/zend-expressive/features/helpers/body-parse/
