### ISSUE TITLE
whmcs issue (zend-diactoros/src/Response/SapiEmitter.php:31 Stack trace: ) 

### ISSUE THREAD

**Issue by Screamfox** [zendframework/zend-diactoros#297]
Hello dear community, 

I am using a module Sinusbot, but when i whant to check the clientpage.php? he give me this error

> code

`exception 'RuntimeException' with message 'Unable to emit response; headers already sent' in /home/htcdocs/public_html/whmcs/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php:31
Stack trace:
#0 /home/htcdocs/public_html/whmcs/clientarea.php(0): Zend\Diactoros\Response\SapiEmitter->emit()
#1 {main}`

some body can help me ? 

Regards,

**Comment by weierophinney** [comment]
That exception occurs when PHP has already sent headers before the emitter has had a chance to emit the Response instance. The following are reasons why that will happen:

- Code has issued an `echo`, `print`, `printf`, `print_r`, `var_dump`, `var_export` or similar statement that writes to the output buffer.
- The `display_errors` setting is enabled in `php.ini`, and a warning, notice, etc. was emitted by your application.

Check your code for cases where any of these may have occurred.

**Comment by Screamfox** [comment]
do you suggest i check the module code or hook code ? 
is a module for whmcs are doing this issue...

thank for help
