### ISSUE TITLE
MessageTrait::setHeaders looses original header name casing.

### ISSUE THREAD

**Issue by rbchasesc** [zendframework/zend-diactoros#300]
According to the [PSR-7 MessageInterface - Case-insensitive header field names](https://www.php-fig.org/psr/psr-7/#case-insensitive-header-field-names), it states:

> Despite that headers may be retrieved case-insensitively, the original case
MUST be preserved by the implementation, in particular when retrieved with
getHeaders().

However, the [`\Zend\Diactoros\MessageTrait::setHeaders`](https://github.com/zendframework/zend-diactoros/blob/master/src/MessageTrait.php#L318) method at [Line 327](https://github.com/zendframework/zend-diactoros/blob/master/src/MessageTrait.php#L327) is performing a `strtolower` on each header name before writing the headers array to to the `headers` protected variable. In doing so, the original header names' case is lost, which appears to be in violation of PSR-7. If this is a violation and to be corrected, it will require changes to other header related methods as they are all assuming the normalization to lowercase for the names has been completed when accessing the `headers` variable.

**Comment by froschdesign** [comment]
@rbchasesc 
>  …before writing the headers array to to the headers protected variable.

Sorry, this is wrong. Look at the next line:

https://github.com/zendframework/zend-diactoros/blob/bb833f8e92297be103bf6cd3fc25219474bbf0d0/src/MessageTrait.php#L327-L328

`$headerNames !== $headers`

See also:

https://github.com/zendframework/zend-diactoros/blob/bb833f8e92297be103bf6cd3fc25219474bbf0d0/src/MessageTrait.php#L20-L32

**Comment by weierophinney** [comment]
As @froschdesign notes, we _do_ keep track of the original casing, and that casing is used when emitting or serializing headers. We normalize the names in `$headers` to allow simplified lookups, but store the originally provided values in `$headerNames`, which is used for representation.
