### ISSUE TITLE
Nested uploaded files parsed wrong in 1.8.0

### ISSUE THREAD

**Issue by aimeos** [zendframework/zend-diactoros#311]
There's a problem in 1.8.0 with nested file uploads for e.g.:
```
<input type="file" name="image[0][file]" />

```
Then, `createUploadedFile()` is called with that array:
```
Array (
	[image] => Array (
		[name] => Array ( [0] => Array ( [file] => admin-product-detail.png ) )
		[type] => Array ( [0] => Array ( [file] => image/png ) )
		[tmp_name] => Array ( [0] => Array ( [file] => /tmp/php9tIgbR ) )
		[error] => Array ( [0] => Array ( [file] => 0 ) )
		[size] => Array ( [0] => Array ( [file] => 83760 ) ) 
	) 
)
```
In version 1.7.2 nested files are correctly parsed

**Comment by precariouspanther** [comment]
Noticed this too - diactoros is allowing single dimension arrays of files (i.e `image[0]`) and named indexes (i.e `image[my-image]`) but not multi-dimensional arrays (i.e `image[0][file]`, `image[slide][0][image][4]`) which are legal names for file upload elements.

**Comment by precariouspanther** [comment]
Candidate fix PR here: https://github.com/zendframework/zend-diactoros/pull/312
