### ISSUE TITLE
fread() expects parameter 2 to be integer, string given in /vendor/zendframework/zend-diactoros/src/Stream.php:277

### ISSUE THREAD

**Issue by jerryhopper** [zendframework/zend-diactoros#333]
Hey there, i encountered this error with this library.

fread() expects parameter 2 to be integer, string given in /vendor/zendframework/zend-diactoros/src/Stream.php:277

### The affected function

File:  Stream.php

```php
public function read($length) : string
    {
        if (! $this->resource) {
            throw Exception\UnreadableStreamException::dueToMissingResource();
        }
        if (! $this->isReadable()) {
            throw Exception\UnreadableStreamException::dueToConfiguration();
        }
        $result = fread($this->resource, $length);
        if (false === $result) {
            throw Exception\UnreadableStreamException::dueToPhpError();
        }
        return $result;
    }
```

### The problem

 fread() expects parameter 2 to be integer, string given in /vendor/zendframework/zend-diactoros/src/Stream.php:277

In this function , you are passing 'length' as a string to fread.

### Temporary solution

as a temporary solution i cast the var to integer.

```php
$result = fread($this->resource, (int)$length);
```

**Comment by Ocramius** [comment]
@jerryhopper the parameter passed to `Stream#read()` is supposed to be an `int` upfront as per its interface: https://github.com/php-fig/http-message/blob/f6561bf28d520154e4b0ec72be95418abe6d9363/src/StreamInterface.php#L127-L129
