### ISSUE TITLE
Stream construction not possible with string

### ISSUE THREAD

**Issue by steffenbrand** [zendframework/zend-diactoros#334]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/c/questions/expressive).)

Stream constructor says it accepts a string, but it doesn't.
Providing a string results in an InvalidArgumentException.
In my opinion, this is misleading.

```php
/**
 * @param string|resource $stream
 * @param string $mode Mode with which to open stream
 * @throws Exception\InvalidArgumentException
 */
public function __construct($stream, string $mode = 'r')
{
    $this->setStream($stream, $mode);
}
```

### Suggestion

Simply remove `string` from `@param string|resource $stream`, because I have a feeling providing a simple string was never intended.

Feel free to correct me ;)

**Comment by froschdesign** [comment]
@steffenbrand 
Are your sure? Please look at:

https://github.com/zendframework/zend-diactoros/blob/83743b4558265e01e74b9da9987441628915d67a/src/Stream.php#L331-L341

https://github.com/zendframework/zend-diactoros/blob/83743b4558265e01e74b9da9987441628915d67a/test/StreamTest.php#L52

https://github.com/zendframework/zend-diactoros/blob/83743b4558265e01e74b9da9987441628915d67a/test/StreamTest.php#L62-L65

**Comment by steffenbrand** [comment]
Ah, sure `php://memory` is a string as well.

Maybe removing the string is not the right suggestion ;) But I think an additional hint would help that the string must actually be a stream identifier, maybe with a link to http://php.net/manual/de/wrappers.php.php.

To be honest, it actually says `must be a string stream identifier or stream resource` in the exception, but I didn't get the meaning of `string stream identifier` at first.

My expectation was, that I could use it like `new Stream('my string that this class is going to wrap in some kind of I/O stream by itself.');`

**Comment by weierophinney** [comment]
@steffenbrand If you are able to upgrade to version 2 (which, unless you are using the emitters or on pre-7.1 versions of PHP, is fully backwards compatible), you can use `Zend\Diactoros\StreamFactory::createString()` to do what you suggest.

We'll definitely accept a patch that would clarify the constructor argument, however.

**Comment by steffenbrand** [comment]
Thank you for the answer!
I guess we can update to ZE 3.2 / Diactoros 2 and use the StreamFactory, as you suggested. :v:

If I come up with a clarifying sentence, I'll provide a PR.
