### ISSUE TITLE
ServerRequest: Header with value "0" discarded

### ISSUE THREAD

**Issue by TCB13** [zendframework/zend-diactoros#342]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/c/questions/expressive).)

When a request is parsed with `ServerRequestFactory` it discards any header set as `0`. 

### Code to reproduce the issue

Create a `client.php`:
```php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PATCH");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, ["Upload-Offset: 0"]);
curl_exec($ch);
```
Create a `server.php` and ask for the `Upload-Offset` header:
```php
$request = Zend\Diactoros\ServerRequestFactory::fromGlobals();
$result = $request->getHeaderLine("Upload-Offset");
```
### Expected results
`$result` should be `0`.

### Actual results
`$result` is set to empty string.

Testing this via xDebug to compare the result of the built in `getallheaders()` with `->getHeaderLine` shows that the issue is in this package:
![headers](https://user-images.githubusercontent.com/6315832/50045252-5ea57f00-0087-11e9-94ed-276d80acc6a2.png)

This issue actually makes it impossible to implement a protocol that requires `Upload-Offset` to always be set even if to zero.

Maybe somehow related to https://github.com/zendframework/zend-http/issues/26 ?

Thank you.

**Comment by malukenho** [comment]
Hello @TCB13!
I've been investigating this issue and I found that whatever header you pass with the value `0` is being removed. You can try with the header `accept` for example.

Without passing the `0` as the header value:
```sh
$ curl -H http://localhost:8089/server.php

# Array
# (
#     [host] => localhost:8089
#     [user-agent] => curl/7.54.0
#     [accept] => */*
# )
```

```sh
$ curl -H 'Accept: 0' http://localhost:8089/server.php

# Array
# (
#     [host] => localhost:8089
#     [user-agent] => curl/7.54.0
# )
```
I'll try to send a patch or at least a test case as soon as possible.

**Comment by TCB13** [comment]
@malukenho thats exactly my problem, I just used `Upload-Offset` as an example. 
Thanks in advance.

**Comment by bluebaroncanada** [comment]
The problem is with the following line, line 38 in `marshal_headers_from_sapi.php`

```
        if ($value && strpos($key, 'HTTP_') === 0) {
```

```
echo !!("0"");
// false
```

So, do we test for `$value === "0"`, or do we `($value || is_string($value) && !empty($value)) && strpos($key, 'HTTP_') === 0`?

**Comment by TCB13** [comment]
@bluebaroncanada ?? wasn't the patch by @malukenho enough to close this issue?

**Comment by bluebaroncanada** [comment]
Read #349 as referenced right above your comment.
