### ISSUE TITLE
get an exeption from ServerRequestFactory::fromGlobals  if i make get req without variables

### ISSUE THREAD

**Issue by newbie78** [zendframework/zend-diactoros#348]
- [ x] I was not able to find an [open](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ x] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/c/questions/expressive).)

when i make get request to https://972bd5f3.ngrok.io/api
server return an exeption about `Invalid header value: must be a string or array of strings; cannot be an empty array`.
if i make request to https://972bd5f3.ngrok.io/api?asd=asd
all work fine

i use
"php": ">=7.2.0",
"zendframework/zend-diactoros": "^2.1",

### Code to reproduce the issue
```
use Zend\Diactoros\ServerRequestFactory;
ServerRequestFactory::fromGlobals($_SERVER, $_GET, $_POST, $_COOKIE, $_FILES)
```

### Expected results

ServerRequestFactory::fromGlobals work without exeptions all time

### Actual results

```
Fatal error: Uncaught Zend\Diactoros\Exception\InvalidArgumentException: Invalid header value: must be a string or array of strings; cannot be an empty array in /var/www/html/vendor/zendframework/zend-diactoros/src/MessageTrait.php:391 Stack trace: #0 /var/www/html/vendor/zendframework/zend-diactoros/src/MessageTrait.php(338): Zend\Diactoros\ServerRequest->filterHeaderValue(Array) #1 /var/www/html/vendor/zendframework/zend-diactoros/src/RequestTrait.php(80): Zend\Diactoros\ServerRequest->setHeaders(Array) #2 /var/www/html/vendor/zendframework/zend-diactoros/src/ServerRequest.php(99): Zend\Diactoros\ServerRequest->initialize(Object(Zend\Diactoros\Uri), 'GET', Object(Zend\Diactoros\PhpInputStream), Array) #3 /var/www/html/vendor/zendframework/zend-diactoros/src/ServerRequestFactory.php(80): Zend\Diactoros\ServerRequest->__construct(Array, Array, Object(Zend\Diactoros\Uri), 'GET', Object(Zend\Diactoros\PhpInputStream), Array, Array, Array, Array, '1.1') #4 /var/www/html/app/route.php(12): Zend\Diactoros\ServerRequestFactory: in /var/www/html/vendor/zendframework/zend-diactoros/src/MessageTrait.php on line 391
```

thanx

**Comment by bluebaroncanada** [comment]
Is this related to #349

**Comment by bluebaroncanada** [comment]
Can you try setting `"zendframework/zend-diactoros": "2.0.1"`

**Comment by newbie78** [comment]
> Can you try setting `"zendframework/zend-diactoros": "2.0.1"`

Yes, there is no error with this version

Thanks
