### ISSUE TITLE
Uncaught TypeError: Return value of Zend\\Diactoros\\Uri::filterQueryOrFragment() must be of the type string, null returned

### ISSUE THREAD

**Issue by YellowPepper** [zendframework/zend-diactoros#357]
```
PHP Fatal error:  Uncaught TypeError: Return value of Zend\\Diactoros\\Uri::filterQueryOrFragment() must be of the type string, null returned in /vendor/zendframework/zend-diactoros/src/Uri.php:660\n
Stack trace:\n
#0 /vendor/zendframework/zend-diactoros/src/Uri.php(618): Zend\\Diactoros\\Uri->filterQueryOrFragment('\\xCF')\n
#1 /vendor/zendframework/zend-diactoros/src/Uri.php(410): Zend\\Diactoros\\Uri->filterQuery('Keyword=\\xCF')\n
#2 /vendor/zendframework/zend-diactoros/src/functions/marshal_uri_from_sapi.php(218): Zend\\Diactoros\\Uri->withQuery('Keyword=\\xCF3')\n
```

Version
 zend-diactoros 2.1.1
 php 7.2.5
### Expected results

TypeError does not occur

**Comment by krowinski** [comment]
+1

**Comment by krowinski** [comment]
+1 

it's returning null because of some regexp error can we use preg_last_error to check and throw exception in filterQueryOrFragment ?

**Comment by weierophinney** [comment]
Can you provide example `$server` and/or `$header` arrays that demonstrate the issue, please? From there we can write a test, which will help us create a fix and prevent a future regression.

Thanks!

**Comment by krowinski** [comment]
@weierophinney Hi, here you go 

```
<?php
var_dump(
    preg_replace_callback(
        '/(?:[^a-zA-Z0-9_\-\.~\pL!\$&\'\(\)\*\+,;=%:@\/\?]+|%(?![A-Fa-f0-9]{2}))/u',
        static function (array $matches) {return rawurlencode($matches[0]);} ,
        ("\x21\x92")
    ), 
    preg_last_error()
);
```

http://sandbox.onlinephpfunctions.com/code/9d90fde0fac05f1d26c0f3310fee3e6cf2405b91

**Comment by weierophinney** [comment]
@krowinski I'm not asking for a patch, I'm asking for a _reproduce case_. I need that so I can write a unit test...

**Comment by krowinski** [comment]
what? this is not a patch its a test how to break preg match to return null, I will fork repo and write test myself

**Comment by krowinski** [comment]
I added too tests example that will fail preg match here 

https://github.com/krowinski/zend-diactoros/commit/81085ad4528bcb25ca505b4f614a824356e02ca7

and travis will fail 
https://travis-ci.org/krowinski/zend-diactoros/jobs/595632127

```
There was 1 error:
1) ZendTest\Diactoros\UriTest::testUtf8Path with data set #2 ('http://example.com/!�', '')
TypeError: Return value of Zend\Diactoros\Uri::filterPath() must be of the type string, null returned
/home/travis/build/krowinski/zend-diactoros/src/Uri.php:590
/home/travis/build/krowinski/zend-diactoros/src/Uri.php:466
/home/travis/build/krowinski/zend-diactoros/src/Uri.php:115
/home/travis/build/krowinski/zend-diactoros/test/UriTest.php:609
```
