### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '?', expecting variable @ marshal_uri_from_sapi.php on line 83

### ISSUE THREAD

**Issue by shivdhwaj** [zendframework/zend-diactoros#374]
I am having PHP version 7.3.9 on my server and Laravel 5.8
PHP(7.0 to 7.3.9) and laravel(5.4 to 5.8) both upgraded 
While deploying code encountering this issue:

> PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /vendor/zendframework/zend-diactoros/src/functions/marshal_uri_from_sapi.php on line 83

**Comment by webimpress** [comment]
@shivdhwaj 
are you sure that you are running PHP 7.3?
The error suggesting that you are on older version...

**Comment by shivdhwaj** [comment]
@webimpress Yes

> php --version
PHP 7.3.9 (cli) (built: Sep 11 2019 02:17:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies

**Comment by webimpress** [comment]
@shivdhwaj This is CLI, is the same for apache/nginx?

**Comment by shivdhwaj** [comment]
@webimpress 7.3 is on the server which holds the complete code, but I am deploying this via a service which is on another server, Do you need to know the same for that server also its a kind of Jenkins service?

**Comment by webimpress** [comment]
@shivdhwaj  So where are you getting the error?
I guess "the middleware" server is not running the code but it's doing just deployment?
If you "build the cache"/"install dependencies" or something like that on the middleware server you would need to have PHP 7.3 there as well.

It looks like issue with PHP version so I would verify it again.

**Comment by shivdhwaj** [comment]
@webimpress I will also look into the deployment service about the same if there is something related to PHP version and update you

**Comment by Ocramius** [comment]
Closing here meanwhile: not an issue with the library itself, but rather with the environment.
