### ISSUE TITLE
PHP Fatal error: require(): Failed opening required zendframework/zend-diactoros/src/functions/create_uploaded_file.php

### ISSUE THREAD

**Issue by hashmat0811** [zendframework/zend-diactoros#384]
I'm getting this error **PHP Fatal error: require(): Failed opening required zendframework/zend-diactoros/src/functions/create_uploaded_file.php**

When I looked into the directory tree there is not folder called **functions** inside zendframework/zend-diactoros/src.

while running composer install/update I'm getting the message Nothing to install or update.

**Comment by michalbundyra** [comment]
@hashmat0811 What version are you using? (Check `composer show`).

The file exists in both:
- 1.8.x - https://github.com/zendframework/zend-diactoros/blob/release-1.8/src/functions/create_uploaded_file.php
- 2.x - https://github.com/zendframework/zend-diactoros/blob/master/src/functions/create_uploaded_file.php

Always you can try remove vendor and run composer install/update again.

**Comment by hashmat0811** [comment]
@michalbundyra, I'm using  1.8.7

**Comment by michalbundyra** [comment]
@hashmat0811 so you see - all is here: https://github.com/zendframework/zend-diactoros/tree/1.8.7/src/functions :)

**Comment by hashmat0811** [comment]
Thanks @michalbundyra, removing vendor and then doing composer install solves the issue.
