### ISSUE TITLE
Cleaner Server semantics

### ISSUE THREAD

**Issue by mindplay-dk** [zendframework/zend-diactoros#40]
The Node paradigm doesn't make any sense under PHP - a Server isn't something that can stay up and process more than one request, or produce more than one response; and the implemented model doesn't support serving more than one request to begin with, since both request and response are injected at the time when Server is constructed. For one, a Server can't "listen" for anything.

Here's a greatly simplified Server implementation with semantics that correspond better with the PHP request/response life-cycle.

```PHP
<?php

namespace xyz; // (ignore this)

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Zend\Diactoros\Response;
use RuntimeException;

/**
 * This class implements server semantics, e.g. processing a request and
 * producing a response, and dispatching a response to the client.
 */
class Server
{
    /**
     * @var callable
     */
    private $callback;

    /**
     * Response emitter to use; by default, uses Response\SapiEmitter.
     *
     * @var Response\EmitterInterface
     */
    private $emitter;

    /**
     * Constructor
     *
     * Given a callback, a request, and a response, we can create a server.
     *
     * @param callable $callback function (ServerRequestInterface $req, ResponseInterface $res) : ResponseInterface
     */
    public function __construct(callable $callback)
    {
        $this->callback = $callback;
    }

    /**
     * Retrieve the current response emitter.
     *
     * If none has been registered, lazy-loads a Response\SapiEmitter.
     *
     * @return Response\EmitterInterface
     */
    public function getEmitter()
    {
        if (!$this->emitter) {
            $this->emitter = new Response\SapiEmitter();
        }

        return $this->emitter;
    }

    /**
     * Set alternate response emitter to use.
     *
     * @param Response\EmitterInterface $emitter
     */
    public function setEmitter(Response\EmitterInterface $emitter)
    {
        $this->emitter = $emitter;
    }

    /**
     * Pipe a given server request through the middleware stack and produce a response.
     *
     * @param ServerRequestInterface $request
     *
     * @return ResponseInterface
     */
    public function process(ServerRequestInterface $request)
    {
        $response = new Response();

        $callback = $this->callback;

        ob_start();

        $response = $callback($request, $response);

        if (! $response instanceof ResponseInterface) {
            throw new RuntimeException("middleware returned invalid or no Response\n" . print_r($response, true));
        }

        return $response;
    }

    /**
     * Dispatch a response to the current connected HTTP client.
     *
     * @param ResponseInterface $response
     */
    public function dispatch(ResponseInterface $response)
    {
        $this->getEmitter()->emit($response);
    }
}
```

Processing a request and dispatching the response isn't a one-liner anymore, but it moves the dependency on Request and Response outside of Server where it belongs, enabling transaction semantics in Server, e.g. provide a Request and get a Response:

```PHP
$server = new Server(new MiddlewarePipe());

$response = $server->process(ServerRequestFactory::fromGlobals());

$server->dispatch($response);
```

This is simpler, and should facilitate easier testing as well, since you can now process a request without actually dispatching it - this should help with integration testing on your middleware stack, assertions about expected responses etc. as the response doesn't need to be sent at all anymore. (To me, this was one of the expected benefits of the request/response abstraction, which we didn't get with this.)

I realize this is a BC break, but I think it's worth considering for version 2.0 - Node semantics seem rather inappropriate for PHP, and modeling Server-style transaction semantics is actually quite a bit simpler. (I doubt anyone will fret over the fact that your front controller script needs two lines of code instead of one.)

Note that we throw if the final result isn't `ResponseInterface` in `process()` - this was a decision about stricter request/response adherence in our environment, and it's probably stricter than what you'd want in your library.

**Comment by Ocramius** [comment]
> a Server isn't something that can stay up and process more than one request 

I beg to differ - long running processes in PHP are perfectly feasible and not necessarily a crazy idea.

Just because it isn't the canonical way of building PHP apps it should not be dismissed. I've been using long running processes (successfully) for a long time and with great advantages.

Also: has nothing to do with nodejs, it's just what app servers do (since ages). Node.js just made it hip to make the http server listener initialization stuff explicit.

**Comment by mindplay-dk** [comment]
> long running processes in PHP are perfectly feasible

Okay, sure, but that's not what this library does.

The `listen()` method doesn't "listen", by any stretch - it doesn't wait for an incoming request, nor does it process multiple requests in a long-running process, it's nothing like a Node app, nor like React, etc... it simply processes the only request/response it can process, the ones given to the constructor.

With the current library, if you wanted to implement it under React or some other long-running process, you'd have to create a new Server instance for every incoming request.

My point was not at all coined on the feasibility of long-running processes in PHP, but the proposed switch to transaction semantics would actually make a lot more sense in that context, too.

**Comment by designermonkey** [comment]
I'm all about semantics, and I prefer these than the current set.

**Comment by mindplay-dk** [comment]
@designermonkey you can simply grab this code and use it now, in place of the standard Server class - we're using it on our project now.

It doesn't matter much (to me) if this is officially included or not - it's a simple class, almost too trivial to bother posting as a separate library. Either way, the important thing to me is middleware compatibility, which we have, so I'm happy either way :-)

**Comment by designermonkey** [comment]
:+1:

**Comment by weierophinney** [comment]
The main purpose of including `Server` in this library was to provide an easy-to-use, predictable way to start playing with PSR-7 messages:

```php
$server = Server::createFromRequest(function ($request, $response) {
    $response->getBody()->write('Hello, world!');
    return $response;
}, ServerRequestFactory::createFromGlobals());
$server->listen();
```

It accomplishes that. The signature of the callable passed as the first argument to `createFromRequest()` and `createServer()` is standard middleware, and that *also* provides an entry point for dispatching PSR-7-based middleware applications. It does *not* mean, however, that this needs to be the *only* way to do so. Emitters were added in large part because of a recognition that folks wanted to emit a response without necessarily using the `Server` semantics.

My point is: I don't disagree that the semantics do not/will not work for everyone's needs. They *do*, however, fulfill the original goals.

I'd definitely accept a PR with an alternate approach; not one that _replaces_ the current approach, but rather a _parallel_ approach. If anybody wants to do so, feel free to open one and reference this issue; until then, I'm closing it.
