### ISSUE TITLE
Cookie helpers

### ISSUE THREAD

**Issue by franzliedke** [zendframework/zend-diactoros#44]
Working with cookies right now is rather tedious, since PSR-7 does not offer any convenience methods (because cookies are essentially headers).

How about a utility class for making cookie manipulation easier?
What should a PR contain?

**Comment by weierophinney** [comment]
I feel such stuff should be in add-on packages; psr-7 was written in part to promote such single purpose utilities and prevent writing framework-specific code. 

@simensen has already begun one such package at https://github.com/dflydev/dflydev-fig-cookies

**Comment by franzliedke** [comment]
Thanks for the tip, I'll use that one.

**Comment by simensen** [comment]
@franzliedke I'm going to be committing something shortly with a slightly different API. If you can hold off a little bit that would be great. Should be in by the end of the night but possibly much sooner. :)

**Comment by franzliedke** [comment]
Thanks for the heads-up, I already implemented it. It's a one-liner, though - does it affect `FigCookies::setResponseSetCookie()`?

**Comment by simensen** [comment]
@franzliedke It will; It is going to be:

```php
$response = FigResponseCookies::set($response, $setCookie);
```

I will hopefully have the docs updated and the change committed in the next 30 minutes.

**Comment by simensen** [comment]
@franzliedke OK, I updated the docs and tagged v1.0.0. What I wrote before is what you will want to change your code to, and you can update your daps to dflydev/fig-cookies ^1.0. Thanks for your patience!

```php
$response = FigResponseCookies::set($response, $setCookie);
```
