### ISSUE TITLE
client

### ISSUE THREAD

**Issue by Mech7** [zendframework/zend-diactoros#53]
is there a plan to create a client in seperate library or does one already exists?

**Comment by sasezaki** [comment]
please update title to clear what is issue.

**Comment by Mech7** [comment]
never mind guzzle has a nice client & message library http://guzzle.readthedocs.org it seems like a better choice for now until this matures a bit.

**Comment by weierophinney** [comment]
> until this matures a bit

@Mech7 This library was developed in tandem with PSR-7, and is fully mature and stable; in fact, it's possible that it's the only current *complete* implementation.

However, the point of this library is only to provide a PSR-7 *implementation*. It does not and will not provide a client library *or* a server-side framework; it's just the messages, plain and simple. Those are *consumers* of a PSR-7 implementation. The messages in this component can be used with such libraries, *including* Guzzle 6 (which also provides implementations of the various client-focused PSR-7 messages).

**Comment by Maks3w** [comment]
Note Guzzle 6 is not a fully PSR-7 compliant. They don't implement ServerRequestInterface and UploadedFileInterface

https://github.com/guzzle/psr7

**Comment by weierophinney** [comment]
@Maks3w which makes sense, as their library is client-focused. They only need to implement what is needed for the client itself.
