### ISSUE TITLE
Why init stream property in the constructor?

### ISSUE THREAD

**Issue by k00ni** [zendframework/zend-diactoros#54]
In the [Response](https://github.com/zendframework/zend-diactoros/blob/master/src/Response.php) class constructor, the **stream** property gets initialized:

```
$this->stream = ($body instanceof StreamInterface) ? $body : new Stream($body, 'wb+');
```

It has no explicit property definition, which means it is public, isn't it? But its usage is not specified in the ResponseInterface of the PSR-7.

My problem is, that the Response class creates files in my project folder. Their name is the same string which i used as `$body` before. I am wondering how to deal with it, because if i implement some specific code to deal with the stream afterwards it will most likely not be compatible with another PSR-7 implementation.

**Comment by Maks3w** [comment]
1. Attribute is public, is the way opted by this library for to preserve the inmutability without to create more methods or instances.

2. MessageInterface::getBody() force the object must return a StreamInterface. This could be lazy load or at constructor time.

**Comment by weierophinney** [comment]
`$stream` is in `MessageTrait` and defined as `private`: https://github.com/zendframework/zend-diactoros/blob/master/src/MessageTrait.php#L41-L44

> My problem is, that the Response class creates files in my project folder.

The `Response` constructor indicates that you should be providing a stream, which can be one of the following:

- a PHP resource
- a `StreamInterface` implementation (such as `Zend\Diactoros\Stream`)

If you provide a `string` value, `Response` interprets this as a **stream identifier**  to use to **create** a stream; in other words, it assumes it is a filesystem path. This is also documented. (See https://github.com/zendframework/zend-diactoros/blob/master/src/Response.php#L108)

If you are trying to pass a string value, your options are:

```php
// Write to the stream after creating the response:
$response = new Response();
$response->getBody()->write($string);

// Create a stream first:
$stream = new Stream('php://temp');
$stream->write($string);
$response = new Response($stream);
```

Or wait until 1.1.0, when #52 is added, and you can do this:

```php
$response = StringResponse::html($html); // HTML contents
$response = StringResponse::json($data); //JSON contents
```

**Comment by weierophinney** [comment]
@Maks3w You're incorrect; the property is defined in `MessageTrait`.

**Comment by k00ni** [comment]
Thanks for the fast answers. I will look into it.
