### ISSUE TITLE
Encoding of "null" or scalar in JsonResponse

### ISSUE THREAD

**Issue by moufmouf** [zendframework/zend-diactoros#63]
Hey @weierophinney ,

This is more of an open question than an issue.

In `JsonResponse`, encoding of "null" is transformed into [].
Encoding of a string like "foo" is transformed into ["foo"].

However, by default,

```
json_encode(null) === "null";
json_encode("foo") === '"foo"';
```

I feel that the default behaviour makes more sense, and is less tricky for the user. However, I guess there must be a reason why you wrap scalar types into arrays, and null into an empty array, but I don't understand why.

For information, in other places (Symfony `JsonResponse`), they seem to transform null into [], but they are not wrapping scalars into arrays. I don't know why either... Any clue why the wrapping?

**Comment by weierophinney** [comment]
@moufmouf The transformation of scalars to arrays was originally proposed by @franzliedke.

The rationale is that, while `json_encode()` and `json_decode()` can deal with scalar values individually, most JavaScript parsers will not; they expect either an array or object as the root. Thus, the `JsonResponse` instance wraps all scalars into an array to allow them to remain valid in those contexts.

**Comment by franzliedke** [comment]
Indeed.

I didn't even remember that this was done for all scalars, too, but that would make sense, I guess.

**Comment by weierophinney** [comment]
@franzliedke It was. :) `null` becomes an empty object, and then any other scalar is wrapped in an array.

I'm thinking of a small change to the code, however; instead of using `ArrayObject` to do an empty object, we can more simply do:

```php
if (null === $data) {
    $data = (object) [];
}
```

and that will be serialized to `{}`, as it will be a `stdClass` instance at that point.

**Comment by franzliedke** [comment]
But we want `[]` for NULL, no?

**Comment by weierophinney** [comment]
@franzliedke I was just using your code. :) I'm not sure it matters; it's an empty value in either case. If we want `[]`, then it becomes even simpler (we don't need to cast at all). See #64 if you want to comment.

**Comment by moufmouf** [comment]
Mmmm... ok, I get the idea.
However, is it still true that most Javascript JSON parser fail to parse null?

Here is a small test:

```
// In Firefox latest, Chrome latest and IE latest, using the standard JSON object:
JSON.parse("null");
> null
JSON.parse("[]");
> Array [  ]
JSON.parse("{}");
> Object {  }

// In jQuery
jQuery.parseJSON("null");
> null
jQuery.parseJSON("{}");
> Object {  }
jQuery.parseJSON("[]");
> Array [  ]
```

I could not find a JSON parser in Javascript that is failing to parse "null". Maybe it is a problem from the past and has been wildly fixed? Is this hack still justified today?

**Comment by franzliedke** [comment]
APIs are often parsed on servers, too. This wasn't part of an older JSON spec, so I'd argue we should go with that.

**Comment by weierophinney** [comment]
More often than not, I expect the JSON returned from an API to be an array or object - something I can iterate or test for properties. As such, a scalar will often result in an error client-side, as the assumptions about what I can do with it fail. So, regardless of whether or not the client *can* parse it is secondary to whether or not I can do with it what I need to do.

**Comment by codeliner** [comment]
But in JS you also have the problem, that you can't handle arrays and objects equally. I often run into the problem that json_encode transforms an empty assoc into `[]` instead of `{}` and then my JS code fails, so I need to cast the empty assoc into ArrayObject or stdClass first on the server. Long story, short. IMO it doesn't make sense to convert scalars into something to help the client, because you cannot be sure what the client expects.

**Comment by moufmouf** [comment]
I tend to agree with @codeliner 

> More often than not, I expect the JSON returned from an API to be an array or object

Completely agree.

> As such, a scalar will often result in an error client-side, as the assumptions about what I can do with it fail.

Indeed, but if the server returns "null" or a scalar, and if it is not supposed to, then the server is the source of the error, not on the client. I would actually expect the client to fail fast, because that would help me pinpoint the problem on the server (i.e. fail fast, fail early)

**Comment by weierophinney** [comment]
I've updated #64 to implement verbatim serialization (vs. casting).

**Comment by codeliner** [comment]
@weierophinney :+1:

**Comment by moufmouf** [comment]
:+1:
