### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by mindplay-dk** [zendframework/zend-diactoros#68]
Me and a colleague have been working hard trying to bypass the error handler - we want to use an alternative error handler ([booboo](https://github.com/thephpleague/booboo)) but the middleware stack catches and handles exceptions before they can get to the error handler.

We noticed the `onerror` callback in `$options` of the `FinalHandler` constructor, but this gets constructed internally in `MiddlewarePipe`, where everything is declared `private`, so we had no luck attempting to extend the class in order to provide the option.

How do we turn off built-in error handling?

**Comment by weierophinney** [comment]
`MiddlewarePipe` and `FinalHandler` are both in Stratigility; is the problem within Stratigility, or within Diactoros? If in Stratigility, can you please open a new issue there?

**Comment by mindplay-dk** [comment]
Whoops, yeah - moved [here](https://github.com/zendframework/zend-stratigility/issues/16) :-)
