### ISSUE TITLE
Output buffering in server class

### ISSUE THREAD

**Issue by mtymek** [zendframework/zend-diactoros#7]
@weierophinney, as discussed yesterday (still on phly/http), I'm back with example use case where Diactoros works together with ReactPHP, creating asynchronous, node-like server.

Here's React PHP-compatible Emitter class:

```php
use React\Socket\Connection;

class Emitter implements EmitterInterface
{
    private $conn;
    public function __construct(Connection $connection)
    {
        $this->conn = $connection;
    }
    public function emit(\Psr\Http\Message\ResponseInterface $response)
    {
        $this->conn->write(ResponseSerializer::toString($response));
    }
}
```

As you can see, it doesn't need to worry about output buffering, it simply sends response via React's Connection object.

Now here's the main server code, returning valid HTTP response saying "Hello world!" for every request. It looks ugly (things like creating Server Request, I want cover that later, in a different PR/issue), but you should get the glimpse on the actual use case. I want to output some debugging information straight to console using `echo`.

```php
$socket = new React\Socket\Server($loop);
$socket->on('connection', function (Connection $conn) {
    $conn->on('data', function ($data) use ($conn) {
	// some debugging info - it will be visible only for the first request
        echo "DEBUG: Incoming request:\n";
        echo $data;

        // create PSR-7 server request from serialized "regular" request
        $request = RequestSerializer::fromString($data);
        $serverRequest = new ServerRequest($_SERVER, [], $request->getUri(), $request->getMethod(), $request->getBody(), $request->getHeaders());

        // prepare PSR-7 response
        $response = new Response();

        // Serve PSR-7 style
        $server = new Server(function (ServerRequest $serverRequest, Response $response) {
            $response = $response->withHeader('Content-type', 'text/html');
            $response->getBody()->write("Hello world!");
            return $response;
        }, $serverRequest, $response);
        $emitter = new Emitter($conn);
        $server->setEmitter($emitter);
        $server->listen();

        // This is not visible because of ob_start() called in listen()
        echo "DEBUG: Requested path: ", $request->getUri()->getPath(), "\n";
        $conn->end();
    });
});
$socket->listen(1337);
```

Full, working example is here: https://github.com/mtymek/react-loop-psr7/.
You can run it from the terminal, open http://localhost:1337/ in your browser, and refresh a few times. Debugging information will be only shown once, before first call to `Server::listen`.

This example shows that output buffering only matters for SAPI, so it should be kept away from "general" `Server` class. IMO it should stay in the `Emitter`, keeping `ob_start` and `ob_flush` together, for code readability.

**Comment by weierophinney** [comment]
The primary issue I see with moving it out of the server class is due to SAPI implementations: in those cases, if the callback attached to `Server` emits to the output buffer at any point, it will break response emission, as headers can no longer be written. Moving the output buffering (specifically, the `ob_start()` call) to the emitter will display exactly that problem.

The other possibility would be to have developers call `ob_start()` *before* calling `listen()`, within their front controller script. However, considering SAPI is still the majority use case, this represents a massive problem, as they must now know to do that ahead of time, and it becomes a source of errors.

As such, for React, it may make more sense to do this:

```php
// inside your connection listener, after setting up the request and response:
$server = function (ServerRequest $serverRequest, Response $response) {
    $response = $response->withHeader('Content-Type', 'text/html');
    $response->getBody()->write('Hello world!');
    return $response;
};

$emitter = new Emitter($conn);
$emitter->emit($server($serverRequest, $response));

// do additional work
```

Notice the change: I define a callback for the server, and don't use `Server`, and I pass the results of that callback (a response) to the emitter directly. It *does* mean that you need your callback to return a response instance, obviously; if you cannot guarantee that, you'd need to do an `instanceof` check before calling `emit()`.

**Comment by mtymek** [comment]
Interesting, looks like `Server` class is not needed at all :-)

When writing that `ob_start` should be located in Emitter class, I actually meant adding new method called inside `Server`'s listen:

```php
class Emitter {
    public function init() {
	  ob_start();
    }
    public function emit(...) {
	  // blah...
    }
}
```

```php
class Server {
    pubic function listen(...) {
	$this->getEmitter()->init();
	// ...
    }
}
```

(likely in such case `Emitter` and `EmitterInterface` would need to be renamed to something better matching what they do)

Anyway, your answer is also good for me :) Do you consider this case closed, or shall I try to follow my proposal and create a PR?

**Comment by weierophinney** [comment]
At this time, I don't want to clutter the Emitter interface with more methods, and I think output buffering should likely be handled elsewhere. For the time being, I'll retain the output buffering in `Server`, as it provides a relatively easy, predictable, out-of-the-box way to play with PSR-7 messages.
