### ISSUE TITLE
Stream as callback

### ISSUE THREAD

**Issue by oscarotero** [zendframework/zend-diactoros#70]
Hi.
I have an application that does some heavy work and I'd like to send to the client a stream with the output of the process. I mean something like this:

```php
use Symfony\Component\Process\Process;

function handler ($request, $response) {
    $process = new Process($command);

    $stream = new StreamCallback(function () use ($process) {
        $process->run(function ($type, $buffer) {
            echo $buffer;
            flush();
        });
    });

    return $response->withBody($stream);
);
```

Is there any way to do something like this?

**Comment by weierophinney** [comment]
We currently only have a single `StreamInterface` implementation, `Zend\Diactoros\Stream`. I'm interested in having additional implementations, and am open to pull requests to implement them.

I did some prototypes in response to questions while we were developing PSR-7, however, and they might interest you:

- https://gist.github.com/weierophinney/7c450a4ab3080c6a0413

**Comment by oscarotero** [comment]
That prototypes looks great. I'll make a PR with a CallbackStream. Thank you
