### ISSUE TITLE
withHeader('Cookie', '...') doesn't work as expected

### ISSUE THREAD

**Issue by mindplay-dk** [zendframework/zend-diactoros#75]
Well, I know the most common use-case is that cookies come already parsed by PHP, e.g. via the `$_COOKIES` superglobal, but... what about middleware attempting to add a 'Cookie' header?

This doesn't work as I expected, e.g.:

```PHP
$request = new ServerRequest(...);

$request = $request->withHeader('Cookie', 'MY_COOKIE=VALUE');

var_dump($request->getCookieParams()); // => array()
```

So this part of the implementation is dependent on `$_COOKIES`, which means it's dependent on PHP's global request context for this feature - it's incapable of actually parsing cookies from headers.

Maybe this is by design, but in my case, it hurts. I now have to detect the cookie header and parse it myself and manually inject the result using withCookieParams() which is messy.

It's also "weird" in relation to the role of Server, which is supposed to take a ServerRequest and produce a Response - you would think - regardless of how that ServerRequest came about. So there is an indirect dependency on superglobals and ServerRequestFactory, and there's an unwritten "law" that you can't read/write cookie headers the same way you would read/write any other headers.

Maybe this disparity is inherent with the spec, I'm not sure - the spec does not say much about cookies and their relationship with headers, it's unclear to me from reading the spec how this was intended to work.

The real problem, I think, is that the PSR model has, effectively, two interfaces to the same data. If you think about the HTTP request, as it was before PHP did it's magic, it did not have a cookie collection which was separate from the header collection, it's just modeled that way, because that's the way it's modeled in PHP - but that doesn't change the fact that means we have denormalization in the model, two representations of the same properties.

Can we fix that?

**Comment by weierophinney** [comment]
> Maybe this is by design,

It is: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message-meta.md#what-about-special-header-values

Essentially: PSR-7 implementations are not expected to, and in fact *should not*, do any special treatment of header values. The specification also makes no allowance for linking the various `ServerRequestInterface` metadata items with their related message counterparts (including headers); bi-directional linking of that sort is out-of-scope and typically impossible to adequately specify.

As such, our recommendation has been to write dedicated libraries for such tasks, and have those *consume* PSR-7 message objects and potentially *manipulate* them (by calling the `with*()` methods and returning new instances with the updates).

@simensen has written a cookie library for exactly this use case you describe: https://github.com/dflydev/dflydev-fig-cookies
