### ISSUE TITLE
PHP version requirment (5.5, was 5.4)

### ISSUE THREAD

**Issue by jkobus** [zendframework/zend-diactoros#8]
Hello.

5.4 was fine for phly/http while this one requires php 5.5. Why ?

**Comment by Maks3w** [comment]
This was elected as minimun version for zend components starting from 2.5

**Comment by jkobus** [comment]
Its the first-and-only implementation of psr7 right now and It would be great if it could support as many platforms as possible.

**Comment by Maks3w** [comment]
Well, PHP 5.4 is deprecated (waiting for formal announcement in the next days) and expected to reach EOL on September.

People should start to migrate to supported PHP versions.

**Comment by samsonasik** [comment]
now it support 5.4 again

**Comment by jkobus** [comment]
True. Refs 8dd06b6c9d40d85d3e92f490863a0295f7a50a74
