### ISSUE TITLE
Parse body for common content types?

### ISSUE THREAD

**Issue by micheh** [zendframework/zend-diactoros#83]
Right now the `ServerRequestFactory::fromGlobals` uses `$_POST` for the parsed body and does not deserialize the request body for common content types (json, xml, etc). Therefore `getParsedBody()` always returns the contents of `$_POST`.

Example: If you have a request with the body `{"foo": "bar"}` and call `getParsedBody()` you get an empty array.

Is this intended/not the responsibility of the request or not implemented yet?

**Comment by weierophinney** [comment]
This is intended.

The factory is intended to seed initial stage based on the superglobal values only. This makes instance creation relatively fast and keeps resource overhead to a minimum.

It is up to the application to decide if further processing should be done, including content negotiation for purposes of marshaling the body content. One reason for delaying this is a performance consideration: if you can determine the request is invalid or unprocessible without parsing, it's better to omit the step (particularly for large payloads, or file uploads).

In PSR-7 apps I've written, I use middleware or a helper to parse and call withParsedBody() only after determining the rest of the request is valid, and usually close to where I'll be using those parameters.

**Comment by micheh** [comment]
@weierophinney I see, thank you for your explanation. Just to clarify your last sentence: With `Zend\Expressive` you would add the parser and the route handler to a `MiddlewarePipe` and then use this middleware pipe as the callable for a route?

**Comment by weierophinney** [comment]
Yes, exactly:

- https://github.com/weierophinney/mwop.net/blob/master/src/Factory/Site.php#L17-L21
- OR: https://github.com/weierophinney/mwop.net/blob/master/config/autoload/global.php#L38-L41
