### ISSUE TITLE
Serialization of Request

### ISSUE THREAD

**Issue by dzentota** [zendframework/zend-diactoros#89]
```php

    public function testSerialization()
    {
        $request = new \Zend\Diactoros\Request('https://example.com', 'GET');
        $serialized = \Zend\Diactoros\Request\Serializer::toString($request);
        $unserialized = \Zend\Diactoros\Request\Serializer::fromString($serialized);
        $this->assertEquals((string)$request->getUri(), (string)$unserialized->getUri());
        $this->assertEquals($request->getHeaders(), $unserialized->getHeaders());
        $this->assertEquals($request->getRequestTarget(), $unserialized->getRequestTarget());
    }
```

```
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'https://example.com'
+'/'

```

Absolute-form of request-target should be used during serialization of Request object because otherwise we lose information about uri schema (https in this case). 
```php
 public function testSerialization()
    {
        $request = new \Zend\Diactoros\Request();
        $serialized = \Zend\Diactoros\Request\Serializer::toString($request);
        $unserialized = \Zend\Diactoros\Request\Serializer::fromString($serialized);
        $this->assertEquals((string)$request->getUri(), (string)$unserialized->getUri());
        $this->assertEquals($request->getHeaders(), $unserialized->getHeaders());
        $this->assertEquals($request->getRequestTarget(), $unserialized->getRequestTarget());
    }
```

```
UnexpectedValueException: Invalid request line detected
```
Maybe there should be another approach for serializing of Request which allows serialization of partial filled objects?

**Comment by dzentota** [comment]
Possible fix is to rewrite getRequestTarget() as:
```php
    public function getRequestTarget()
    {
        if (null !== $this->requestTarget) {
            return $this->requestTarget;
        }

        if (! $this->uri) {
            return '/';
        }
        return (string) $this->uri;
    }

```

**Comment by weierophinney** [comment]
I get your point. However, the specification for `getRequestTarget()` is such that it will return the origin-form **always**, unless you have specifically set the request target using `withRequestTarget()`. In your example, you did not do so, which is equivalent to the following message:

```http
GET / HTTP/1.1
Host: example.com
```

The request target is of interest only when actually making a request, and is used to make the connection in the first place. As such, I'd argue the current behavior is correct; otherwise, we end up with absolute-form by default, which is, frankly, not used often, and unexpected in most instances.

To get the behavior you want, you would need to call `withRequestTarget()` to generate a new request with the absolute-form; once you do, serialization will work as expected.

```php
$request = (new \Zend\Diactoros\Request('https://example.com', 'GET'))->withRequestTarget('https://example.com/);
```

Serialize that, and what you have returned can be deserialized with the request target intact.

**Comment by dzentota** [comment]
This is weird that your Request can be serialized only from time to time. When I'm serializing something (in most cases, exception resources) I expect to get the same item when I deserialize one back. In your case it is not obvious that I should do some kind of preparation before serialization. 

I'm ok with your tip about withRequestTarget but I don't understand why object can be serialized without error but can NOT be deserialized back - I get exception. 

```php
        $request = new \Zend\Diactoros\Request();
        $serialized = \Zend\Diactoros\Request\Serializer::toString($request);
        $unserialized = \Zend\Diactoros\Request\Serializer::fromString($serialized);
```

From my point of view it's better to throw exception on serialization - 

```php
    public static function toString(RequestInterface $request)
    {
        if (empty($request->getMethod())){
            throw new UnexpectedValueException("Your object can not be serialized at this state. Please specify method");  
        }
        ...
    }  
```

at least you'll get Exception immediately

**Comment by weierophinney** [comment]
Question: is the URI not correct after deserialization/serialization? If it's correct, then, again, I'm not entirely certain what problems you're observing...

**Comment by dzentota** [comment]
After deserialization I get Exception. This is because method (e.g GET) is not specified, so in the method below $requestLine ===  'https://example.com HTTP/1.1'


```php

    private static function getRequestLine(StreamInterface $stream)
    {
        $requestLine = self::getLine($stream);
        if (! preg_match(
            '#^(?P<method>[!\#$%&\'*+.^_`|~a-zA-Z0-9-]+) (?P<target>[^\s]+) HTTP/(?P<version>[1-9]\d*\.\d+)$#',
            $requestLine,
            $matches
        )) {
            throw new UnexpectedValueException('Invalid request line detected');
        }
  ...
```

So, my point is - I need an ability to serialize Requests and Responses at any stage (after instantiation or after applying any number of methods) and I need an ability to deserialize it back at least without Exception

**Comment by dzentota** [comment]
From your doc:
```
The deserialization methods (from*()) will raise exceptions if errors occur while parsing the message. The serialization methods (toString()) will raise exceptions if required data for serialization is not present in the message instance.
```
So, if I don't see exception on serialization then ```required data IS present```. But then I try to deserialize it back and see an Exception because ```required data IS NOT present```. That is why I've made a proposal to throw Exception on serialization if object has state in which it can not be serialized - ```required data IS NOT present```, e.g method is not specified.

**Comment by weierophinney** [comment]
@dzentota Would you be willing to create a pull request to fix the behavior?

**Comment by dzentota** [comment]
Yes, if you can confirm that described approach in my previous comment is the proper one.

**Comment by weierophinney** [comment]
@dzentota It does. TBH, the de/serialization stuff was added late, and is quite basic at this point. Any help you can provide would be appreciated!

**Comment by dzentota** [comment]
@weierophinney I made a PR https://github.com/zendframework/zend-diactoros/pull/112. So now it should not throw exceptions for serialized requests with empty method. But it seems that it is impossible to write De/Serializer which implements RequestInterface or MessageInterface and will be able to restore exact state of the object which was serialized because `getRequestTarget` in some case (request-target is not specified) returns not the actual value (null) but '/' (as specification requires). So if you serialize request object with empty request-target then after deserialization it will have request-target == '/'. 
But we can implement serializer of Request instead of RequestInterface. E.g we can add method e.g. getRawRequestTarget (which will return exact value of request target (e.g. null) ) and use it in serializer
```php
public function getRawRequstTarget()
{
    return $this->requestTarget;
}
``` 
or we can change format of the serialized request, e.g `serilze(getAllPropertiesFromObject($request))` so after deserialization request object can be initiated with the exact values

**Comment by weierophinney** [comment]
@dzentota — The reason `getRequestTarget()` is setup to return `/` when no request target is present is to ensure a valid target is present for purposes of serialization; a `null` request target has no meaning, and leads to an invalid request line. If the request target returned `null`, I'd argue the serializer **MUST** raise an exception, as it can not create a valid representation. I'd argue the same fact for #112; lack of the method in the request line is an indication of an invalid request, and we should not serialize it, nor should we be able to deserialize a request that omits either one of those pieces of data from the request line.

**Comment by dzentota** [comment]
I agree. What I want to say is: it depends on the goal you want to achive, if you want to get the properly formatted string (from HTTP spec perspective) after serialization then of course method and request target MUST present, but if you don't care about intermediate format (what you are actually get after serialization) but only want to be able to store this somewhere (e.g. queue) and then deserialize it back in another script in the same state then method and request target CAN be omitted

**Comment by weierophinney** [comment]
@dzentota — The goal here is definitely de/serialization of *valid* messages. If you want something that does de/serialization regardless of validity, that would be outside the scope of what we want to provide, and is something for your own library or application. If it's a feature that proves popular, we can revisit it at a later date.

It's possible we need to raise exceptions when serializing messages that are missing some data; however, IIRC:

- we never allow an empty request method
- the request target defaults to `/` when not present

which means you cannot serialize an invalid request line at this time.
